### ISSUE TITLE
Orthotypo - Intégration dans le thème

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#176]
- [ ] Vérifier l'intégrité
- [ ] Supprimer le système de nettoyage typo

**Comment by alexisben** [comment]
Je comprends pas ?

**Comment by arnaudlevy** [comment]
Quand @pabois aura merge dans l'admin, l'HTML devrait être pré-filtré. 
Il faudra vérifier le rendu, et supprimé les scripts de nettoyage HTML.
