### ISSUE TITLE
[beautify code] Dropdown

### ISSUE THREAD

**Issue by alexisben** [osunyorg/theme#196]
Créer un component dropdown pour nettoyer les différents dropdowns. Liste non exhaustive des usages : 
- Diplomas select
- i18n footer
- header (voir si celui là n'est pas trop spécifique)

**Comment by Olivia206** [comment]
Est-ce que tu as bossé dessus depuis ? Il y a un `@mixin dropdown-i18n` qui permet de gérer le cas du i18n dans le header et le footer
