### ISSUE TITLE
Workflow Percy

### ISSUE THREAD

**Issue by SebouChu** [osunyorg/theme#243]
En gros, tu fais une PR sur le thème genre `new-feature` :
- Déclenchement de workflow
- Création d’une branche `theme--new-feature` sur [osuny-example](https://github.com/noesya/osuny-example) à partir de `main`
- Sur cette nouvelle branche, commit pour pointer le submodule sur le dernier commit de `new-feature`
- Push de cette branche -> déclenchement Percy

**Comment by alexisben** [comment]
- [ ] Réussir à faire parler percy dans le Slack

**Comment by alexisben** [comment]
On arrête Percy on cherche autre chose
