### ISSUE TITLE
Problème d'accessibilité

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#259]
https://www.elodiechardon.fr/poemes/
Signalé par Johan Senn : 
* Je n'ai pas l'impression que votre solution intègre ARIA. Des changement de contexte, la page courante, ne sont pas signalés. 
* Je suis allé voir sa page "poème", personnellement, étant aveugle, le contenu ne m'est pas restitué, si ce n'est des bouton intitulé "image", tous identiques.

**Comment by alexisben** [comment]
Shit le bouton d'ouverture de la lightbox block la lecture de l'image

**Comment by Olivia206** [comment]
Ajouter un `aria-describedby` ou un `aria-description` au lien/bouton de la lightbox pourrait peut-être régler ce problème ? 
(la deuxième option évite d'ajouter un élément au dom)
