### ISSUE TITLE
Pb des classes ajoutées dans l'admin

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#271]
Quand on ajoute une classe sur une page, elle s'ajoute sur tous les enfants

**Comment by arnaudlevy** [comment]
On pourrait  
- créer des classes différentes 
- créer des catégories de pages

`full-image` les enfants auraient `ancestor-full-image`

**Comment by arnaudlevy** [comment]
Etapes : 
1. ajouter ancestor- dans le static @arnaudlevy 
2. utiliser les nouvelles ancestor dans CODE @alexisben 
3. enlever les non-ancestor dans le static @arnaudlevy

**Comment by alexisben** [comment]
duplicate https://github.com/osunyorg/theme/issues/289
