### ISSUE TITLE
Recherche pagefind

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#308]
- [x] Revoir l'exclusion pagefind dans osuny.js (retirer pages / sections a minima ?)
- [ ] Hiérarchiser le contenu de la recherche ([rankings](https://pagefind.app/docs/weighting/))
- [ ] Documenter

Exemple : [IUT BM](https://github.com/noesya/bordeauxmontaigne-iut/issues/87)

**Comment by arnaudlevy** [comment]
J'ai l'impression que les h1 sont ignorés.

Il y a longtemps, les balises header étaient exclues, mais ça semble avoir été réparé.

**Comment by arnaudlevy** [comment]
https://github.com/CloudCannon/pagefind/issues/75

**Comment by alexisben** [comment]
@SebouChu on comprend pas comment corriger ça

**Comment by arnaudlevy** [comment]
@SebouChu tu trouves ?

**Comment by arnaudlevy** [comment]
@SebouChu tu oublies pas ?

**Comment by arnaudlevy** [comment]
@SebouChu c'est fixed non ? Même si le balisage n'est pas pur
