### ISSUE TITLE
Mise à jour des chemins de submodules

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#325]
### Déplacement du submodule

Déplacement du répertoire du submodule
```
git mv themes/osuny-hugo-theme-aaa themes/osuny
```

Changement de l'URL
- Si HTTPS :
  ```
  git submodule set-url -- themes/osuny https://github.com/osunyorg/theme.git
  ```
- Si SSH :
  ```
  git submodule set-url -- themes/osuny git@github.com:osunyorg/theme.git
  ```

Modifier le fichier `.gitmodules` pour remplacer `[submodule "themes/osuny"]` par `[submodule "themes/osuny"]` puis appliquer la modification du nom du submodule avec `git submodule update --init --recursive`.

### Mise à jour du package.json

```
{
  "name": "osuny-template",
  "version": "6.0.0",
  "repository": "https://github.com/osunyorg/template",
  "author": "osunyorg",
  "license": "MIT",
  "dependencies": {
    "osuny": "./themes/osuny"
  },
  "scripts": {
    "osuny": "npx osuny-hugo-theme"
  }
}
```

Si un lockfile (`yarn.lockl` ou `package-lock.json`) est présent, il faut relancer l'installation des dépendances avec l'outil correspondant (`yarn install` ou `npm install`)

### Mise à jour de la config (config/_default/config.yaml)

```
theme: osuny
```

### Gestion de l'ancienne version du thème

Il est nécessaire pour l'ancienne version du thème d'avoir l'ancien chemin (`themes/osuny-hugo-theme-aaa`) fonctionnel (pour la config PostCSS par exemple). Pour cela, depuis la racine du repository du site, il faut créer un lien symbolique comme ceci :
```
ln -s osuny themes/osuny-hugo-theme-aaa
```

Une fois la nouvelle version du thème déployée, le lien symbolique en sera plus nécessaire et on peut le supprimer.

### Application

Une fois les modifications effectuées, on peut commit et push. 

### Mise à jour du package.json

```
{
  "name": "osuny-hugo-theme",
  "version": "6.0.0",
  "repository": "git@github.com:osunyorg/theme.git",
  "author": "alexisben <alexis.benoit@noesya.coop>",
  "contributors": [
    "olivia206 <olivia.simonet@noesya.coop>",
    "alexisben <alexis.benoit@noesya.coop>",
    "arnaudlevy <arnaud.levy@noesya.coop>",
    "clararigaud <clara.rigaud@noesya.coop>"
  ],
  "license": "MIT",
  "dependencies": {
    "@splidejs/splide": "^4",
    "cssnano": "^5",
    "cssnano-preset-advanced": "^6.0.1",
    "glightbox": "^3",
    "intersection-observer": "^0",
    "leaflet": "^1",
    "pagefind": "^1",
    "postcss": "^8",
    "postcss-cli": "^9",
    "postcss-sass": "^0",
    "shelljs": "^0"
  },
  "bin": "./bin/osuny.js"
}
```

### Mise à jour du theme.yaml

```
licenselink: 'https://github.com/osunyorg/theme/blob/main/LICENSE'
```

### Mise à jour du workflow test-with-example.yml

Lignes 23 à 29 
```
      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          repository: osunyorg/theme
          token: ${{ secrets.OSUNY_EXAMPLE_TOKEN }}
          path: themes/osuny
          ref: ${{ github.head_ref || github.ref_name }}
```

### Mise à jour du CLI

Ligne 86
```
    execute("cd themes/osuny");
```

### Mise à jour du partial CSS
@alexisben pourquoi ?

Ligne 8
```
{{- $postCSSOpts := (dict "config" "osunyorg/theme") -}}
```

**Comment by alexisben** [comment]
@arnaudlevy ```{{- $postCSSOpts := (dict "config" "osunyorg/theme") -}}``` indique le chemin du fichier postcss.config.js

**Comment by arnaudlevy** [comment]
@SebouChu et ça c'est ok ?
