### ISSUE TITLE
Classes personnalisées dans les blocks et les titres

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/theme#339]
(Comme dans le cas des pages)

**Comment by arnaudlevy** [comment]
Ce serait bien oui

**Comment by alexisben** [comment]
Issue à sur https://github.com/noesya/osuny

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/admin/issues/1721

**Comment by arnaudlevy** [comment]
C'est une issue côté thème, une côté admin, j'ai fermé par erreur
