### ISSUE TITLE
Ancestor-class ne s'applique pas sur toutes les classes personalisées

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/theme#340]
Si je met deux classes sur une page parente ex: "classe-1 classe-2", le prefix ancestor ne s'applique que sur la premiere classe dans les pages enfants: "ancestor-classe-1 classe-2"
Je propose "ancestor-classe-1 ancestor-classe-2"

**Comment by alexisben** [comment]
Issue pour https://github.com/noesya/osuny
