### ISSUE TITLE
Problème de z-index

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#347]
https://site.degrowthcommunication.osuny.site/media/social-media-posts/
<img width="1792" alt="Capture d’écran 2024-03-19 à 10 38 38" src="https://github.com/osunyorg/theme/assets/2088968/d98b9f1b-4deb-44cb-ade1-2b4f7ac6eee3">

La TOC n'est pas cliquable alors que les images semblent visuellement derrière

**Comment by alexisben** [comment]
Corrigé !
