### ISSUE TITLE
Marges incohérentes

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#358]
<img width="1792" alt="Capture d’écran 2024-04-01 à 10 39 14" src="https://github.com/osunyorg/theme/assets/2088968/750ee566-0326-410a-b5da-8c12275ff281">

https://commune-libre-d-aubervilliers.pdr.osuny.site/le-projet/

**Comment by alexisben** [comment]
C'est passé par erreur directement sur la main mais on devrait être mieux désormais !
