### ISSUE TITLE
Bloc contact

### ISSUE THREAD

**Issue by alexisben** [osunyorg/theme#504]
mauvais affichage sur PC Chrome 

![image](https://github.com/osunyorg/theme/assets/4630530/af1ab315-1d9b-497b-9d07-879b004586ec)

https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/

**Comment by Olivia206** [comment]
J'ai regardé ce qui pouvait causer ça sur les pc, mais je mets en standby mes recherches comme ma connexion ne permet pas de faire fonctionner BrowserStack de façon stable. 

En tout cas, ça vient de notre grille, de façon assez invariable, sur pc, les colonnes ont l'air de prendre pour `--column-width` 64px, au lieu de varier. Il me semble avoir identifié que le problème vient du `--grid-width`, la fonction min() semble pourtant [bien supportée](https://caniuse.com/?search=min()), à voir si c'est ça ou non.

Aussi, en dézoomant, tout se remet bien sur la grille dès lors qu'on atteint la valeur maximale de notre container.
-> vérifier qu'on ne rencontre pas ce pb sur des tailles intermédiaires d'écran, même sur mac

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/theme/pull/544

**Comment by Olivia206** [comment]
@alexisben la PR de @Clararigaud était un fix de secours
Le problème existe toujours il me semble : y'a un pb de calcul des colonnes sur windows
