### ISSUE TITLE
Nettoyage des formations

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#520]
On utilise les formations à plusieurs endroits, et alors qu'on pourrait avoir un seul partial de liste avec des options et des paramètres, on a pléthore de `<ol class="programs">`, ce qui est assez dommage.

**Comment by alexisben** [comment]
Effectivement, c'est un héritage du vieux thème. On a des programs dans : 
- themes/osuny/layouts/partials/programs/programs.html
- themes/osuny/layouts/partials/programs/children.html
- themes/osuny/layouts/partials/programs/programs-list.html
- themes/osuny/layouts/partials/blocks/templates/programs.html
- themes/osuny/layouts/partials/programs/program.html
- themes/osuny/layouts/partials/persons/programs.html
- themes/osuny/layouts/partials/locations/template-program.html
