### ISSUE TITLE
Actualités : ajout d'une balise sémantique pour les dates

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#547]
On utilise actuellement la balise `<time>`, or elle ne peut exister seule car :   

> Parents autorisés : Tout élément qui accepte du contenu phrasé.
https://developer.mozilla.org/fr/docs/Web/HTML/Element/time

![Capture d’écran 2024-08-14 à 15 13 50](https://github.com/user-attachments/assets/c8ab9594-e67f-40b1-bba4-3038e35a52cd)

**Comment by Clararigaud** [comment]
aussi dans agenda

**Comment by Olivia206** [comment]
En réalité `<time>` est une balise à valeur sémantique : 
- https://developer.mozilla.org/fr/docs/Web/HTML/Element/time
- https://developer.mozilla.org/fr/docs/Glossary/Semantics
