### ISSUE TITLE
Carousel - positionner les fleches de controle après le carousel

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/theme#555]
10.3 - Bloquant : Présence d’une information dont l’ordre dans le code source ne
permet pas sa compréhension par les utilisateurs de technologies d'assistance, les
flèches de navigation sont positionnées avant le carrousel

- Positionner les flèches de navigation à la suite du carrousel

**Comment by arnaudlevy** [comment]
Le pb c'est l'html ou le css ?

**Comment by Clararigaud** [comment]
> Le pb c'est l'html ou le css ?

C'est le html, les contrôles doivent être après le contenu, ce n'était pas le cas mais c'est fix ( l'apparence est inchangée)
