### ISSUE TITLE
Réparer les liens sociaux

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#564]
https://esee-degrowth2024.uvigo.gal/en/

<img width="1792" alt="Capture d’écran 2024-08-19 à 16 06 25" src="https://github.com/user-attachments/assets/d38e4d7c-53cb-42e0-8e85-a775527311f1">

**Comment by Olivia206** [comment]
Réparé ici : https://github.com/osunyorg/vigo-internationaldegrowthconference2024/commit/6976ac9de01610df58805306a59a36b7478dba25
