### ISSUE TITLE
TOC

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#565]
- [x] Rendre accessibles les liens
- [x] Ajouter un titre au toc -> `role="heading"` (`aria-level="2"` implicite)

![Capture d’écran 2024-08-19 à 16 55 47](https://github.com/user-attachments/assets/404fcaa6-8154-4b6f-974f-e9303cb5f5d2)

**Comment by arnaudlevy** [comment]
Tu peux mettre en bold l'élément en cours dans le thème

**Comment by Olivia206** [comment]
Ok !
