### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#567]
> Ajouter sur à l'élément span.note un attribut aria-expanded dont la valeur sera à true lorsque le panneau .note_content est visible,  false lorsque le panneau n'est pas visible (par exemple au chargement de la page)

- [x] Ajout de l'attribut `aria-expanded="false"` dans le static @arnaudlevy 
- [x] Modification de l'attribut en js

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/theme/pull/569
