### ISSUE TITLE
Visibilité de la prise du focus clavier : logo header / footer, iframe, cta, marker map et lightbox

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/theme#574]
8.2. Visibilité de la prise du focus clavier
10.7 - majeur : pour chaque élément recevant le focus, la prise du focus clavier doit
être visible. Ce n’est pas le cas pour quelques éléments interactifs du site.

Soit laisser outline par défaut du navigateur | Soit style personnalisé ne reposant pas seulement sur un changement de couleur (soulignement)

Lien image, focus peu visible : il y a bien un focus présent et ce n'est pas une non
conformité, mais ce focus est beaucoup moins visible que certains focus sur images, il
serait judicieux d'encadrer la totalité de l'mage avec le focus visible

● Rétablir la visibilité de prise du focus sur tous les éléments interactifs dans toutes les
pages du site
○ Soit en ne dégradant pas l’outline par défaut du navigateur
○ Soit en s’assurant qu’un style personnalisé ne reposant pas seulement sur un
changement de couleur est présent sur chaque élément concerné, le
soulignement par exemple

**Comment by arnaudlevy** [comment]
@Olivia206 j'ai designé ça dans Figma
