### ISSUE TITLE
Bloc tableau : remplacer <caption> par <summary>

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/theme#578]
5.5 - Majeur : Présence d’un titre de tableau peu pertinent, le contenu de la balise
caption reprend l&#39;intégralité des informations données dans le tableau

Rendre le titre du tableau plus pertinent en identifiant le contenu du tableau de
façon claire et concise

**Comment by Clararigaud** [comment]
De ce que je comprends il y a deux choses différentes: la caption qui est un descriptif du tableau genre "les colonnes indiquent X, les lignes indiquent Y"

Et la transcription qui est un paragraphe complet qui explique ce que le tableau nous apprend. 

Il faut ajouter un champs caption dans l'admin qui arra dans la balise caption. 
Et que ce qui est actullement transcription textuelle aille dans un paragraphe distinct

**Comment by Clararigaud** [comment]
On peut peut etre mettre ca dans la liste des chose à discutter demain :)

**Comment by Olivia206** [comment]
J'ai cru comprendre du rapport d'audit que <caption> doit identifier le titre, mais on pourra voir demain, oui

**Comment by Clararigaud** [comment]
@Olivia206  on laisse tomber ça du coup ?

**Comment by Olivia206** [comment]
En partie ! Si on part du principe qu'on n'aura pas de tableau de données complexes, il faut que `<caption>` correspondre au titre du tableau (donc changements à prévoir en admin (pour enlever le "transcription" et rajouter un court champ de texte) et ajustement dans le thème comme on ne reçoit pas la même donnée (à vérifier))
Tu en penses quoi ?

**Comment by Clararigaud** [comment]
Je pensais à ca aussi. Dans le theme il n'y a rien de sémantique ( juste une balise <caption> ) donc changer dans l'admin "transcription" en "titre" ou "caption" devrait suffire pour l'a11y

**Comment by Clararigaud** [comment]
Ticket correspondant en admin > https://github.com/osunyorg/admin/issues/2154
