### ISSUE TITLE
Marker de carte sans intitulé explicite

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/theme#579]
7.1 - Majeur : Présence d&#39;un intitulé non explicite sur le bouton
● 7.1 - Majeur : L’état affiché / masqué du panneau d&#39;aide n’est pas indiqué aux
technologies d’assistance

Ajouter un intitulé explicite sur le bouton, par exemple &quot;Afficher / masquer l&#39;adresse
du campus&quot;
● Ajouter sur cet élément &lt;button&gt; un attribut aria-expanded dont la valeur sera à true
lorsque le panneau est visible, false lorsque le panneau n&#39;est pas visible

**Comment by Clararigaud** [comment]
@Olivia206  @arnaudlevy  c'est généré dans leaflet . je fais quoi ?

**Comment by arnaudlevy** [comment]
j'ai pas le contexte ni l'url, je comprends pas

**Comment by Clararigaud** [comment]
> j'ai pas le contexte ni l'url, je comprends pas

https://example.osuny.org/fr/campus/iut-bordeaux-montaigne/ la carte en bas
