### ISSUE TITLE
Témoignages : changement d'alignement si image ou non

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#619]
+ uniformiser entre slider et pas slider

![image](https://github.com/user-attachments/assets/91e2002e-7651-4f49-947a-c7f69d236700)

**Comment by arnaudlevy** [comment]
@Olivia206 je pense que j'ai fait une erreur de le mettre à gauche quand y a pas d'image, je change dans le figma

**Comment by arnaudlevy** [comment]
J'ai repris le figma, dis moi ton avis

**Comment by Clararigaud** [comment]
https://carousel-a11y--example-osuny.netlify.app/fr/blocks/blocks-narratifs/temoignages/
