### ISSUE TITLE
Slideshow correctifs

### ISSUE THREAD

**Issue by alexisben** [osunyorg/theme#621]
Desktop et mobile
- [x] La description du bloc sort du flux à droite (en mobile aussi)
![image](https://github.com/user-attachments/assets/87ce171b-9b9e-46fd-9867-88ebea1de0f7)

Desktop
- [x] Quand on navigue avec les flèches du clavier vite le numéro de la slide fait n'importe quoi
- [x] Quand on navigue avec les flèches du clavier vite le slideshow glitch (il passe d'une slide à une autre sans transition)
- [ ] Quand je change de slide parfois le header (menu principal) s'affiche et la page se décale verticalement

https://github.com/user-attachments/assets/682ffe73-46c4-480e-9f55-0e50e6e9b79b

Mobile
- [ ] Quand on scroll vers le haut puis vers le bas dans une page qui a un slideshow, ça resize le slideshow et créer un "saut" pendant la navigation (du au resize en hauteur des images)
- [ ] Quand on swipe et change de slide le numéro de la slide ne se synchronise qu'une fois l'animation terminée
- [ ] Parfois je peux pas changer de slide en swipant

https://github.com/user-attachments/assets/33815ac8-38c4-443f-a176-03931b93b3f1

**Comment by alexisben** [comment]
Il y a des erreurs html sur le bloc post en mode carousel, des <li> qui ne sont pas dans une liste.

![image](https://github.com/user-attachments/assets/847a0ee2-8ea1-472c-8fc8-2ddc8bec0384)

Il ne faut pas non plus pourrir le template générique post.html (utilisé à 13 endroits différents dans le thème) avec du spécifique pour un type d'affichage du bloc post : 

<img width="674" alt="image" src="https://github.com/user-attachments/assets/280c4eca-d9bd-40f7-a1ab-fe3f5da4e955">

**Comment by alexisben** [comment]
L'overflow du bloc posts en mode carousel doit être visible. À droite il doit être visible jusqu'à la fin de l'écran, à gauche les slides doivent passer en opacité sous la table des matières et si pleine largeur l'overflow doit être visible sur toute la largeur de l'écran.

![image](https://github.com/user-attachments/assets/ef23ded3-90b1-4018-a8d5-c5876f5997b1)

![image](https://github.com/user-attachments/assets/ae640f74-b6eb-40dc-ba59-f2ffb5a581fa)

Fonctionnement précédent : 

![image](https://github.com/user-attachments/assets/b4d2d72c-b400-4f99-a12b-1f1c8cf35a3e)

**Comment by alexisben** [comment]
Il y a-t-il un intérêt (ou une bonne pratique ?) à passer tout par des events ? 

Par exemple dans `themes/osuny/assets/js/theme/components/carousel/carousel.js`, il faut tout un bazar pour instancier l'autoplayer, il y a de la logique concernant l'autoplayer dans la classe `Carousel`. Pourquoi ne pas instancier un autoplayer en lui passant en référence l'instance du Carousal pour qu'ils puissent communiquer directement ?

Au lieu de ça : 
```
_initializeAutoplayer () {
        this.autoplayerElement = this._findElement('autoplayerToggle');
        this.autoplayer = new window.osuny.carousel.Autoplayer(this.autoplayerElement);
        this.autoplayer.setInterval(this.config.autoplayinterval);
        this.autoplayer.ariaLiveElement = this._findElement('container');
        if (this.autoplayerElement) {
            this.autoplayerElement.addEventListener(window.osuny.carousel.events.autoplayerTrigger, this.next.bind(this));
            this.autoplayerElement.addEventListener(window.osuny.carousel.events.autoplayerProgression, this._onAutoplayerProgression.bind(this));
            if (this.config.autoplay) {
                this.autoplayer.enable();
            }
        }
    },
```

on aurait ça : 

```
 this.autoplayer = new window.osuny.carousel.Autoplayer(this);
```

**Comment by Olivia206** [comment]
Pour l'opacité, il me semble que la maquette n'est plus à jour, c'est bien volontaire !

**Comment by Olivia206** [comment]
Pour les témoignages, lors que le dernier témoignage voit son onglet changer, on est automatiquement remonté au niveau du bloc : https://example.osuny.org/fr/blocks/blocks-narratifs/temoignages/

**Comment by alexisben** [comment]
En pleine largeur les overflow doivent être visibles

![image](https://github.com/user-attachments/assets/bd593927-7385-4834-ac65-33f5ccb861f9)

**Comment by alexisben** [comment]
iphone SE - Firefox

- [ ] Le focus sur la slide pète le scroll, ça reste bloqué sur la slide : 

https://github.com/user-attachments/assets/01524540-2cdd-41cd-8832-ea75263bf7de

- [ ] Après avoir jouer avec une timeline, le menu par en cacahuète (il y a un effet chelou sur le menu sur d'autres pages aussi quand le menu est ouvert et qu'on arrive à scroller dans la page : c'est p-e du au scroll intermittent que déclenche le slider)

![IMG_8914](https://github.com/user-attachments/assets/b7767d87-abd2-4322-905d-4ac1915731b5)
![IMG_8913](https://github.com/user-attachments/assets/99809a91-bf66-409e-9be2-99fb56b279e7)


- [ ] Le focus sur la timeline est partiellement visible, du coup ça fait juste un effet chelou

![IMG_8912](https://github.com/user-attachments/assets/f0d67299-6dd0-4dfd-886d-c325f9cf8164)
