### ISSUE TITLE
Changer l'ordre map/liste sur la page des campus

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#630]
Inverser la carte pour qu'elle aille sous la liste : https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/sites-formation/

**Comment by alexisben** [comment]
On est bon pour ça @Olivia206  ?

**Comment by Olivia206** [comment]
Non, maintenant on doit propose une option pour afficher une carte dans l'index des campus, sur le modèle de la page d'un campus
