### ISSUE TITLE
Header - Menu mobile et bouton burger 

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#747]
- modifier le aria-label du  
`<button type="button" aria-controls="navigation" aria-expanded="false" aria-label="Ouvrir / Fermer le menu" class="header-button">` par “menu” (amélioration)
- à minima quand menu ouvert si le focus sort du header (event focusout) fermer automatiquement le menu (idéalement faire boucler le focus dans le header jusqu'à fermeture du menu) (conformité)
- quand utilisateur ouvre le menu déplacer dans l'ordre du code source le nav.upper-menu après le nav avec le aria-label menu principal  (conformité)

**Comment by arnaudlevy** [comment]
## Problème

### URL

Sur quelle URL peut-on observer le problème ?

TODO

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by arnaudlevy** [comment]
@goetsu vu avec @alexisben, le point 3 ne semble correspondre à aucun critère, il nous semble que c'est une proposition d'amélioration de ta part et pas une non-conformité. Ok ?

**Comment by goetsu** [comment]
point 2 nav clavier mobile oui car ça invalide le 10.7 (et avec voiceover/talkback le lecteur d'écran restitue effectivement le contenu derrière le menu mais ça je ne l'ai pas invalidé en tant que tel meme si c'est pas optimum)
point 3 NC 10.3

**Comment by arnaudlevy** [comment]
Point 3 c'est effectivement de se retaper le upper-menu à la vocalisation. Il devrait venir après le menu, je trouve, comme une possibilité de changer de site.

**Comment by alexisben** [comment]
Pour le point 3 on peut envisager : 

```
<header id="document-header" role="banner">
  <nav aria-label="Menu principal">
    <div class="container">
      <a class="logo with-darkmode" href="https://example.osuny.org/fr/"
        title="Accueil - Example">
        [...]
      </a>
      <button type="button" aria-controls="navigation" aria-expanded="false" aria-label="Ouvrir / Fermer le menu"
        class="header-button">
        [...]
      </button>
      <div class="menu" id="navigation">
        [...]
      </div>
    </div>
  </nav>
  <nav class="upper-menu" aria-label="Menu d'accès rapide">
    [...]
  </nav>
</header>
```

**Comment by goetsu** [comment]
oui par contre c'est à faire uniquement quand on ouvre le menu pour ne pas impacter l'ordre du code en desktop (en amélioration on peut également le remettre à sa place à la fermeture du menu pour éviter en cas d'usage responsive de plus avoir le menu à la bonne place si on reswitch en affichage desktop)

**Comment by alexisben** [comment]
@goetsu ces trois points sont traités, est-ce ok pour toi ?

**Comment by goetsu** [comment]
au final vous avez fait boucler le focus dans le menu ce qui est très bien mais qui du coup nécessite en complément d'ajouter un aria-hidden="true" sur les enfants du body sauf le header quand on ouvre le menu puis les supprimer si on referme le menu de cette manière le lecteur d'écran ne pourra pas non plus sortir du menu / header quand il est ouvert

**Comment by alexisben** [comment]
Est-ce correct d'ajouter un attribut `inert` sur tout ce qui ne concerne pas le menu quand il est ouvert en mobile @goetsu ? 

Le code est testable sur https://example.osuny.org/

**Comment by goetsu** [comment]
je ne vois pas de changement sur [exe](https://example.osuny.org/) cela dit le support de inert par les lecteurs d'écrans est moins bon que aria-hidden donc je recommanderais plutot d'utiliser ce dernier d'autant qu'ici inert n'apportera rien par rapport à aria-hidden vu que tu as déjà bloqué le focus dans le menu

**Comment by goetsu** [comment]
ok
