### ISSUE TITLE
[a11y] block page 

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#750]
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-pages

- supprimer les p vide dans le div.description (conformité)
`<div class="description"><p></p><p>xxxx</p><p></p></div>`

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-pages

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by arnaudlevy** [comment]
@goetsu ça c'est un pb de contribution, cela fait très longtemps que les textes sont nettoyés de leurs `p` vides, mais ce texte avait été contribué avant cela. J'ai réparé, et je ferme.
