### ISSUE TITLE
[a11y] - page accessibilité

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#751]
supprimer le `<ul class="files"></ul>` vide actuellement dans le code source après le texte "Cette déclaration d'accessibilité s'applique au site https://example.osuny.org." (conformité)

**Comment by arnaudlevy** [comment]
## Problème

### URL

Sur quelle URL peut-on observer le problème ?

TODO

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by arnaudlevy** [comment]
@goetsu c'est un template de déclaration, ce n'est pas à évaluer.
Par ailleurs il y a un de petits éléments à changer à partir de la déclaration fournie par Temesis.
Le mieux, il me semble, est de mettre le bloc en draft à la génération.
