### ISSUE TITLE
Bloc vidéo

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#752]
https://example.osuny.org/fr/blocks/blocks-de-base/videos/
https://example.osuny.org/fr/actualites/2023-03-04-referentiel-general-decoconception-de-services-numeriques-rgesn/
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-videos

- ajouter dans le bouton permettant de lancer la video un <span class="sr-only">Lancer la vidéo - xxx</span> où xxx = titre de la vidéo (conformité)
- soit supprimer le aria-label et le title sur le bouton soit ajouter le titre de la video dans le aria-label et le title sur le bouton permettant de lancer la vidéo title="Lancer la vidéo - xxx" aria-label="Lancer la vidéo - xxx" où xxx = titre de la vidéo (amélioration)
- utiliser un alt="" sur l'image placeholder (conformité)
- ajouter un id unique et un aria-hidden="true" sur le p contenant le titre de la video  (conformité)
- ajouter un aria-describedby="xxx" où xxx = valeur de l'id du p contenant le titre de la vidé sur le bouton transcription  (conformité)
- attention en back office la contribution du titre de la vidéo devrait etre obligatoire à minima

**Comment by arnaudlevy** [comment]
@goetsu en admin, le titre en obligatoire est une mauvaise solution, les gens contournent en mettant n'importe quoi.
En revanche on pourrait tenter une récupération automatique du titre sur la plateforme.

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/admin/issues/2446

**Comment by alexisben** [comment]
![image](https://github.com/user-attachments/assets/4da1a755-f7db-41cc-b396-5bab549cabe8)

**Comment by goetsu** [comment]
@arnaudlevy dans ce cas 
si titre contribué on prend celui là
si pas de titre contribué on prend celui de la plateforme via api

**Comment by alexisben** [comment]
C'est corrigé en ligne sur example

**Comment by goetsu** [comment]
ok sauf ce point c'est bien ça "pas de titre contribué on prend celui de la plateforme via api" ?

**Comment by arnaudlevy** [comment]
@goetsu l'issue est créée côté thème, dans tous les cas on n'a pas d'API pour Dailymotion et Peertube, donc il faudra auditer la contrib

**Comment by goetsu** [comment]
oui donc 7.1 à auditer à chaque fois
