### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#753]
https://example.osuny.org/fr/agenda/2024-02-03-charbel-joseph-h-boutros-the-sun-is-my-only-ally/

- ajouter une liste pour structurer la liste des liens dans `<li class="events-actions">`
<img width="278" alt="image" src="https://github.com/user-attachments/assets/4f59f8f1-1e27-461f-995a-fbef7e3066fd">

**Comment by arnaudlevy** [comment]
## Problème

### URL

Sur quelle URL peut-on observer le problème ?

TODO

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by alexisben** [comment]
C'est ok pour ce point

**Comment by alexisben** [comment]
Ok pour toi @goetsu ?

**Comment by goetsu** [comment]
ok pour moi, petite question au niveau de bloc date en back office c'est une saisie libre ou ils saisissent plusieurs date individuellement ? si oui en amélioration possible passer également les différentes dates en sous liste
```
<li class="event-date" itemprop="startDate" content="2024-02-03"><span>Date</span>
<ul><li>Samedi 3 février 2024</li><li>Mardi 28 avril 2026</li></ul></li>
```
