### ISSUE TITLE
Bloc personnes

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#754]
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-personnes
https://example.osuny.org/fr/agenda/2024-02-03-charbel-joseph-h-boutros-the-sun-is-my-only-ally/

- supprimer les p vide (conformité)
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/4eae8b3a-68d5-4173-ad75-c345856771d6">
<img width="497" alt="image" src="https://github.com/user-attachments/assets/80fa94e3-58a1-47e4-bfd2-daf66c8aac7f">

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-personnes
https://example.osuny.org/fr/agenda/2024-02-03-charbel-joseph-h-boutros-the-sun-is-my-only-ally/

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by alexisben** [comment]
Ce point est corrigé, ok pour toi @goetsu ?

**Comment by goetsu** [comment]
ok pour moi
