### ISSUE TITLE
Bloc organisations - layout carte

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#755]
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-organisations

- ajouter un role="region" et un aria-label="Vue cartographique - xxx - se déplacer avec les flèches du clavier" où xxx = titre de la carte sur la div.organizations map leaflet-container (conformité)
- bouton + / -, traduire le aria-label et title et ajouter un aria-describedby="xxx" où xxx = titre de la carte  (conformité)
- remplacer la div.leaflet-control-attribution leaflet-control par un p  (conformité)
- supprimer le title sur le lien leaflet ou le remplacer par "Leaflet une librairie javascript pour carte intéractive"  (conformité)
- bouton de fermeture des blocs description des pin : traduire le aria-label "Close popup" et ajouter dans le aria-label l'intitulé du pin pour avoir "Fermer details point d'intérêt - xxx" où xxx = titre du pin  (conformité)
`<a class="leaflet-popup-close-button" role="button" aria-label="Close popup" href="#close"><span aria-hidden="true">×</span></a>`
<img width="325" alt="image" src="https://github.com/user-attachments/assets/21d65b5e-5510-4be3-99a5-e6cdf5cdd03e">

- ajouter un aria-describedby="xxx" sur le summary "données textuelles" où xxx = valeur de l'id du titre de la carte  (conformité)
- le titre de la carte devrait etre obligatoire en contribution

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-organisations

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by arnaudlevy** [comment]
@alexisben @Olivia206 remplir le code pb / solution, ajouter l'historique des échanges, confronter avec la doc developers

**Comment by alexisben** [comment]
@goetsu on croyait qu'il fallait enlever les pin de la carte ? 

https://developers.osuny.org/docs/theme/components/carte/

**Comment by alexisben** [comment]
@goetsu on est bon pour ces différents points !
