### ISSUE TITLE
Bloc contact 

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#756]
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-contacts

- remplacer le `<p itemprop="name">` par un h4 (conformité)
- remplacer les `<p>` adresse, web, horaire, téléphone, réseau sociaux, email par des h5  (conformité)
- sortir le `<li class="meta">Horaires</li>` du li et le remplacer par un h5  (conformité)

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-contacts

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by goetsu** [comment]
ok pour moi
