### ISSUE TITLE
Bloc témoignages - carrousel

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#757]
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-temoignages

- ajouter le contenu du `<span class="meta">` dans le aria-label du figure  (conformité)
- supprimer le aria-selected des bouton de controle du carrousel (amélioration) `<button aria-selected="false" class="carousel__pagination__page" type="button" aria-controls="js-carousel-1-item-1" aria-describedby="title-js-carousel-1" aria-current="false"> 
<span class="sr-only">Aller l'élément 2
</span><i style="width: 0%;"></i></button>`
- bouton play / pause, il y a actuellement l'intitulé des deux état dans le bouton il ne devrait y avoir que l'intitulé correspondant à l'état actif du bouton exemple `<span class="sr-only">Carousel en cours de lecture. Mettre en pause le carousel.</span>` quand le carrousel est en lecture (conformité)

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-temoignages

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by alexisben** [comment]
Pour garder la trace : 

Le markup validator du w3c remonte cette erreur :

"A figure element with a figcaption descendant must not have a role attribute."

Mais cela devrait être effectivement un warning et non pas une erreur : https://github.com/validator/validator/issues/1336

**Comment by alexisben** [comment]
@goetsu, est-ce qu'on peut utiliser un `aria-description` sur les boutons de pagination, qui reprend le texte du titre du bloc ou par défaut "Carousel X" (où x est le numéro du bloc) ?

Un `aria-describedby` semblerai plus optimal, mais comme le titre du bloc n'est pas obligatoire, cela permet d'avoir toujours une description aux boutons ?

![image](https://github.com/user-attachments/assets/67f50769-8b44-490f-a072-7b356721d175)

**Comment by alexisben** [comment]
Autre proposition, ajouter une balise `<p aria-hidden="true" id="slider-1-title">Les témoignages</p>` et utiliser un `aria-describedby="slider-1-title"` ? Ça évite la redondance de texte dans le html.

**Comment by goetsu** [comment]
le support de aria-description n'est pas encore optimum (et pas présent par le RGAA à ce jour donc formelllement meme si ça fonctionnait on pourrait pas le valider)
Donc conserver la solution du aria-describedby pour le fait de masquer ou non le titre via aria-hidden je ne suis pas fan dans ce contexte car cela permet d'introduire le bloc avant meme la restitution des boutons

**Comment by alexisben** [comment]
Dans ce cas, on peut gérer en fonction de la présence d'un titre du bloc : 

## Cas 1 : bloc avec titre  

```HTML
<div class="block block-testimonials block-titled">
  <div class="container">
    <div class="block-content">
      <div class="top sr-only">
        <h3 class="block-title" id="slider-title-0">Les témoignages</h3>
      </div>

      <div class="slider is-ready"
        style="--slider-transition-duration: 250ms; --slider-pagination-interval: 5000ms; touch-action: pan-y;">
        <div class="slider-track">
          <div class="testimonials slider-list"
            data-slider="{&quot;autoplay&quot;:true,&quot;interval&quot;:5000,&quot;pagination&quot;:true}"
            style="transform: translateX(-717px);">
            <figure class="testimonial slider-slide is-current" role="figure"
              aria-label="Auteur.e du témoignage, Métier de l'auteur.e" aria-hidden="true">
              [ ... ]
            </figure>
            [ ... ]
          </div>
        </div>
        <div class="slider-controls">
          <ul class="slider-pagination" aria-label="Pagination du carrousel" aria-describedby="slider-title-0">
            <li>
              <button aria-describedby="slider-title-0" aria-current="true">
                <span class="sr-only">Aller à l'élément 1</span>
              </button>
            </li>
            <li>
              <button aria-describedby="slider-title-0" aria-current="false">
                <span class="sr-only">Aller à l'élément 2</span>
              </button>
            </li>
            <li>
              <button aria-describedby="slider-title-0" aria-current="false">
                <span class="sr-only">Aller à l'élément 3</span>
              </button>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
```

## Cas 2 : bloc sans titre

```HTML
<div class="block block-testimonials">
  <div class="container">
    <div class="block-content">
      <p class="sr-only" id="slider-title-18">Carrousel 18</p>
      <div class="slider is-ready"
        style="--slider-transition-duration: 250ms; --slider-pagination-interval: 5000ms; touch-action: pan-y;">
        <div class="slider-track">
          <div class="testimonials slider-list"
            data-slider="{&quot;autoplay&quot;:true,&quot;interval&quot;:5000,&quot;pagination&quot;:true}"
            style="transform: translateX(-717px);">
            <figure class="testimonial slider-slide is-current" role="figure"
              aria-label="Auteur.e du témoignage, Métier de l'auteur.e" aria-hidden="true">
              [ ... ]
            </figure>
            [ ... ]
          </div>
        </div>
        <div class="slider-controls">
          <ul class="slider-pagination" aria-label="Pagination du carrousel" aria-describedby="slider-title-18">
            <li>
              <button aria-describedby="slider-title-18" aria-current="true">
                <span class="sr-only">Aller à l'élément 1</span>
              </button>
            </li>
            <li>
              <button aria-describedby="slider-title-18" aria-current="false">
                <span class="sr-only">Aller à l'élément 2</span>
              </button>
            </li>
            <li>
              <button aria-describedby="slider-title-18" aria-current="false">
                <span class="sr-only">Aller à l'élément 3</span>
              </button>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by goetsu** [comment]
oui très bien
