### ISSUE TITLE
Bloc Frise chronologique — layout horizontal & Actualités — layout carrousel

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#758]
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-frises-chronologiques
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-actualites
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-galeries

- à l'activation des bouton < et > il faut déplacer le focus sur le `<article>` / `figure` qui devient complètement visible exemple A visible B visible C partiellement visible D masqué, j'active > focus déplacé sur C car c'est lui qui devient complétement visible et on a alors A masqué, B visible, C visible, D partiellement visible (conformité)

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-frises-chronologiques
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-actualites
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-galeries

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by alexisben** [comment]
- Modifier le html de la progression pour :`<p>2<span class="sr-only"> sur </span><span aria-hidden="true">/</span>4</p>`
- aria-describedby sur les flèches
- aria-describedby sur le bouton play/pause
- enlever aria-describedby et aria-label sur le `<ul>`

On conserve la navigation un par un comme elle cohérente avec la pagination.

@goetsu

**Comment by alexisben** [comment]
En amélioration ne pas ouvrir afficher menu en mobile en scroll up déclenché par un focus d'un slider

**Comment by alexisben** [comment]
C'est ok pour les différents points, pour que ce soit plus confortable les blocs en mode carousels sont tous consultables ici : https://example.osuny.org/fr/actualites/2024-11-28-les-carousels-dosuny/

**Comment by goetsu** [comment]
je ne vois pas de changement sur cette url + il manque le point sur le passage du tabindex 0 à tabindex -1 sur les slides qui récupère le focus après activation des bouton < et >

**Comment by alexisben** [comment]
Pardon j'ai raté le deploy hier soir, c'est ok maintenant !
