### ISSUE TITLE
Bloc son 

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#759]
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-sons

- ajouter un id unique et un aria-hidden="true" sur le p contenant le titre de la video  (conformité)
- ajouter un aria-describedby="xxx" où xxx = valeur de l'id du p contenant le titre du son sur le bouton transcription  (conformité)
- attention en back office la contribution du titre de la vidéo devrait etre obligatoire à minima

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-sons

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by alexisben** [comment]
@goetsu on a appliqué les correctifs, c'est à jour sur https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-sons

**Comment by goetsu** [comment]
c'est ok et du coup en back office le titre est obligatoire ?

**Comment by alexisben** [comment]
Il n'est pas obligatoire mais un warning remonte dans l'espace d'administration s'il n'est pas renseigné !

**Comment by goetsu** [comment]
ok du coup on aura un critère 7.1 à vérifier possiblement à chaque usage du composant en audit décliné

**Comment by alexisben** [comment]
Je ferme ce ticket et j'ajoute dans la doc ton retour : https://developers.osuny.org/docs/theme/blocks/sound/
