### ISSUE TITLE
Bloc Image

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#760]
https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-images
https://example.osuny.org/fr/actualites/2024-11-18-la-nouvelle-visionneuse-dosuny/

cas image seul 
- l'image devrait avoir un alt générique "illustration" ou mieux "illustration x" où x = numéro de l'image seul dans la page, si une alternative à l'image est contribué en back office (qui n'est pas la légende) alors c'est cette alternative qui se retrouve dans le alt de l'image (conformité)
- mettre l'image dans le button permettant de l'agrandir après le `<span class="sr-only">Agrandir l'image</span>`de cette manière il n'est pas nécessaire de reprendre le alt de l'image dans le sr-only (conformité)

cas image + légende sans copyright
- ajouter un id unique sur le figcaption (conformité)
- l'image devrait avoir un alt générique "illustration" ou mieux "illustration x" où x = numéro de l'image seul dans la page, si une alternative à l'image est contribué en back office (qui n'est pas la légende) alors c'est cette alternative qui se retrouve dans le alt de l'image (conformité)
- ajouter un aria-describedby="xxx" sur le button où xxx= valeur de l'id du figcaption (conformité)
- mettre l'image dans le button permettant de l'agrandir après le `<span class="sr-only">Agrandir l'image</span>`de cette manière il n'est pas nécessaire de reprendre la légende ou le alt de l'image dans le sr-only (conformité)
- supprimer les `<p>` vide dans le figcaption (conformité) 
<img width="716" alt="image" src="https://github.com/user-attachments/assets/5e579cab-607d-4cd5-841c-8ae4e06faa42">

cas image + copyright sans légende
- ajouter dans le aria-label des `figure` le © au début de ce texte exemple aria-label="© Daniel Faro  - lien externe, Death to the stock" (conformité)
- remplacer le sigle copyright actuellement généré via css dans le texte des crédits par un © dans le code (conformité)
- ajouter un id unique sur le figcaption (conformité)
- l'image devrait avoir un alt générique "illustration" ou mieux "illustration x" où x = numéro de l'image seul dans la page, si une alternative à l'image est contribué en back office (qui n'est pas la légende) alors c'est cette alternative qui se retrouve dans le alt de l'image (conformité)
- ajouter un aria-describedby="xxx" sur le button où xxx= valeur de l'id du figcaption (conformité)
- mettre l'image dans le button permettant de l'agrandir après le `<span class="sr-only">Agrandir l'image</span>`de cette manière il n'est pas nécessaire de reprendre le alt de l'image dans le sr-only (conformité)

cas image  + legend + copyright
- ajouter dans le aria-label des `figure` le contenu du div.credit quand présent en prenant soin d'inclure le © au début de ce texte et d'enlever les liens exemple aria-label="Ordinateur © Daniel Faro  - lien externe, Death to the stock" (conformité)
- remplacer le sigle copyright actuellement généré via css dans le texte des crédits par un © dans le code (conformité)
- ajouter un id unique sur le figcaption (conformité)
- l'image devrait avoir un alt générique "illustration" ou mieux "illustration x" où x = numéro de l'image seul dans la page, si une alternative à l'image est contribué en back office (qui n'est pas la légende) alors c'est cette alternative qui se retrouve dans le alt de l'image (conformité)
- ajouter un aria-describedby="xxx" sur le button où xxx= valeur de l'id du figcaption (conformité)
- mettre l'image dans le button permettant de l'agrandir après le `<span class="sr-only">Agrandir l'image</span>`de cette manière il n'est pas nécessaire de reprendre la légende ou le alt de l'image dans le sr-only (conformité)
- supprimer les `<p>` vide dans la legende dans le figcaption (conformité) 
<img width="716" alt="image" src="https://github.com/user-attachments/assets/5e579cab-607d-4cd5-841c-8ae4e06faa42">

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/blocks/blocs-de-mise-en-page/#les-images
https://example.osuny.org/fr/actualites/2024-11-18-la-nouvelle-visionneuse-dosuny/

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by alexisben** [comment]
> A1. l'image devrait avoir un alt générique "illustration" ou mieux "illustration x" où x = numéro de l'image seul dans la page,  si une alternative à l'image est contribué en back office (qui n'est pas la légende) alors c'est cette alternative qui se retrouve dans le alt de l'image (conformité) 

Le `alt` avec un texte comme "illustration" semble être contradictoire avec le [1.1.1](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#1.1.1) : si l'image n'est pas porteuse d'information, elle sera tout de même restituée au lecteur d'écran. Cela pose problème car les personnes contributrices ne pourront plus déterminer si l'image n'est pas porteuse d'information en laissant l'attribut `alt` vide.

**Comment by Olivia206** [comment]
Bonsoir @goetsu !

Je me permets de rebondir sur le sujet des textes alternatifs.

Sur Osuny, la visionneuse ne se limite pas au seul cas des images ayant des alt, car ce n'est pas sa seule fonction, il n'y a donc pas d'images avec ou sans visionneuse. Son utilité première est de permettre une meilleure visualisation à la fois de l’image et des informations disponibles, peu importe la nature de l'image.

Dans les cas que tu cites, un `alt="illustration"` ou générique donnerait une information non pertinente (critère 1.3) et ajouterait également une étape de lecture au lecteur d’écran utilisé, qui restituerait « Image. Illustration », et il me semble que ce qui n’est pas très utile, surtout quand on cherche à éviter la verbosité ?

Mais surtout, je peux tout à fait être une personne qui voit un peu mal, qui a mal aux yeux, ou tout simplement qui a repéré un joli visuel, qui n’a pas de signification (ou dont la signification est portée par le texte), et qui agrandit l’image pour simplement mieux voir, car sur certains écrans c’est quand même très petit. La visionneuse n’a pas de fonction purement informative. D’ailleurs le texte, l’alt ou le crédit sont de toute manière restitués en dehors de celle-ci.

Il me semble difficile de priver les gens de cette fonctionnalité parce qu'il s'agit d'image sans alt/utilité propre ?

**Comment by goetsu** [comment]
comme déjà si l'image est tout seule, qu'elle ne peut pas etre ouverte dans la visionneuse pas de souci avec alt="" par défaut sauf si elle a un credit ou une légende dans ce cas il faut également un alt générique à minima surchargeable en cas de contrib de l'alternative en back office

Si l'image s'ouvre dans la visionneuse alors elle ne peut pas avoir alt vide ni dans la visionneuse ni en dehors

**Comment by arnaudlevy** [comment]
@goetsu je comprends ce que tu dis, mais nous sommes très gênés par ta suggestion d'alt générique, @Olivia206 @alexisben et moi.

Concrètement, d'après le W3C :
- si c'est [une image informative (cas 4)](https://www.w3.org/WAI/tutorials/images/informative/#example-4-images-conveying-an-impression-or-emotion), il faut un alt spécifique (pas un générique)
- Si c'est [une image décorative (cas 4)](https://www.w3.org/WAI/tutorials/images/decorative/#example-4-image-used-for-ambiance-eye-candy), il faut un alt vide. 

La visionneuse n'a pas de rapport avec ça, c'est soit informatif et il faut un alt, soit décoratif et il n'en faut pas. 

Par ailleurs, c'est la première fois qu'on entend cette préconisation d'un alt générique, j'aimerais bien une source pour appuyer ce que tu dis. 
1. Le W3C dit "Usually, there’s no need to include words like “image”, “icon”, or “picture” in the alt text" (https://www.w3.org/WAI/tutorials/images/tips/). 
2. Le WCAG dit "Don’t write “image of” or “pic of”  (https://www.wcag.com/blog/good-alt-text-bad-alt-text-making-your-content-perceivable/). 
3. [L'arbre de décision W3C](https://www.w3.org/WAI/tutorials/images/decision-tree/) n'a aucun cas qui aboutit à un alt générique. 
4. Userway identifie ce que tu conseilles comme [une mauvaise pratique](https://userway.org/fr/blog/balise-alt/) : Utiliser des descriptions non descriptives (Mauvaise pratique `alt=″Graphique″`).
5. Pendant leur formation RGAA avec Access42, il a été clairement dit à @alexisben et @Olivia206 de ne pas mettre d'alt générique comme "logo" ou "photo".
 
Nous ne pouvons pas nous satisfaire d'un argument d'autorité, il y a 100 sites Web en production et une communauté de personnes qui s'appuient sur Osuny. Il faut que les choix soient sourcés, surtout s'ils sont contre-intuitifs. Si c'est quelque chose qui n'a pas de source officielle, ou qui est débattu dans la communauté A11Y, alors ça ne peut constituer une non-conformité. En revanche, ça serait très intéressant d'en parler avec des personnes directement concernées pour définir la meilleure façon de faire. Merci beaucoup !

**Comment by goetsu** [comment]
je ne dis pas que c'est la solution idéale, la solution idéale c'est que toutes les images dans la visionneuse dispose d'un alt décrivant l'image puisque dans ce contexte elles ne peuvent etre décorative

Imaginons un instant que le alt de l'image dans la visionneuse soit vide car vous considérez qu'elle est décorative : 
* cas 1 image sans alternative contribuée, sans legende ou copyright et hors galerie j'ai donc annoncé à l'utilisateur "agrandir l'image", une fois l'image agrandi dans la visionneuse je n'ai aucune image annoncée puisque alt vide
* cas 2 image sans alternative contribuée, avec legende ou copyright et hors galerie j'ai donc annoncé à l'utilisateur "agrandir l'image", une fois l'image agrandi dans la visionneuse je n'ai aucune image annoncée puisque alt vide et une légende / crédit qui ne fait reference à rien
* cas 3 image sans alternative contribuée, avec legende ou copyright et galerie j'ai donc annoncé à l'utilisateur "agrandir l'image", une fois l'image agrandi dans la visionneuse je n'ai aucune image annoncée puisque alt vide, une légende / crédit qui ne fait reference à rien et des boutons images suivantes / précédante qui quand je les active me renvoie me vocalise rien puisque image avec alt=""

c'est la meme problematique dans un carrousel de photo hors visionneuse elles ne pourront pas avoir un alt vide meme si en théorie décorative car il y a interaction avec ces images sinon j'interagis avec rien ou pour une image avec légende / copyright

A noter pour éviter le vocalisation de "agrandir l'image illustration" on peut envisager d'utiliser "image" ou "image x" où x numéro de l'image et d'utiliser juste "agrandir" dans le sr-only du bouton car si on ajoute le alt de l'image dans le bouton cela fera bien "agrandir image" ou "agrandir image x".

Après si vous ne voulez pas le faire pas de souci le critère 1.3 sera juste non conforme par défaut sauf contribution manuelle de toutes les alternative d'image puisque l'image n'est pas décorative dans ce contexte (et que de toute façon le critère sera aussi non conforme si vous utilisez "image" et non "image x" tel que suggéré si j'ai plusieurs images sans alternative dans la meme page qui ouvre la visionneuse)

**Comment by arnaudlevy** [comment]
Merci pour l'explication, je crois que je comprends : c'est fondamentalement un pb de contribution. Et si on supprimait les lightbox sur les images sans alt (et tant pis pour les personnes dans le cas décrit par @Olivia206) ? @goetsu Tu en penses quoi ? Moindre mal ? Et on peut dire en admin que si y a pas de bras y a pas de chocolat.

**Comment by goetsu** [comment]
Pour moi effectivement j'aurai tendance à dire qu'une image "décorative" n'a pas de plus value à être agrandie. Si l'image doit pouvoir être agrandie c'est qu'elle apporte qqchose et donc que cette information apportée par l'image doit se retrouver dans le alt exemple une photo d'un tableau et dans le alt je met "paysage champêtre dans un champ de coquelicots avec un mère femme tenant une ombrelle et un enfant en premier plan et une autre femme et un enfant à l l'arrière plan." avec le copyright © Musée d’Orsay, Dist. RMN-Grand Palais / Patrice Schmidt et la description Claude Monet Coquelicots; 1873; huile sur toil; H. 50,0 ; L. 65,3 cm.

**Comment by Olivia206** [comment]
Rebonjour @goetsu 

Pour les crédits `© `, on souhaiterait savoir s'il est possible d'avoir un `<p class="sr-only">Crédit :</p>` à côté du crédit, pour restituer cette information

**Comment by goetsu** [comment]
pas sûr de bien comprendre la question / but

**Comment by Olivia206** [comment]
Afin que l'information du © soit restituée sans css, tu nous as indiqué plus haut qu'il faut le passer dans le contenu et non en before/after.

On aimerait savoir s'il est possible de plutôt mettre un équivalent ("crédit :") à côté du contenu du crédit, uniquement vocalisé ou visible en cas de désactivation du style.

**Comment by goetsu** [comment]
Actuellement le © affiché via le before est vocalisé sur les lecteurs d'écrans gérant les contens css du coup il faudrait être alors certains que le contenu en before et after ne soit vocalisé avec aucun lecteur d'écran en utilisant la technique dont nous avons discuté sinon si on utilise du texte masqué il y a une double vocalisation ou sinon faire `<span aria-hidden="true"></span><span class="sr-only">Droits réservés : </span> xxxx` en application le content css sur le span avec la aria-hidden (il faudra également bien reprendre ce texte dans le aria-label

**Comment by alexisben** [comment]
Les différents points ont été traités ! Ok pour toi @goetsu ?

**Comment by goetsu** [comment]
pourriez vous faire une page de recette avant l'ensemble des cas possibles

image sans visionneuse 
- sans alt contribué sans legende sans crédit
- sans alt contribué sans legende avec crédit
- sans alt contribué avec legende sans crédit
- sans alt contribué avec legende avec crédit

image sans visionneuse 
- avec alt contribué sans legende sans crédit
- avec alt contribué sans legende avec crédit
- avec alt contribué avec legende sans crédit
- avec alt contribué avec legende avec crédit

image avec visionneuse 
- sans alt contribué sans legende sans crédit
- sans alt contribué sans legende avec crédit
- sans alt contribué avec legende sans crédit
- sans alt contribué avec legende avec crédit

image avec visionneuse 
- avec alt contribué sans legende sans crédit
- avec alt contribué sans legende avec crédit
- avec alt contribué avec legende sans crédit
- avec alt contribué avec legende avec crédit

**Comment by Olivia206** [comment]
Bonjour @goetsu, on a repris la page d'actu des Lightbox pour te mettre chaque cas : https://example.osuny.org/fr/actualites/2024-11-18-la-nouvelle-visionneuse-dosuny/

Dans les bloc de galerie, il n'y a pas de lightbox, on a donc fait un cas sans et avec alt, tu trouveras toutes les infos annotées
Dans les blocs d'image, en revanche, on a bien la lightbox, avec les 4 premières images sans alt et les 4 suivantes avec (les titres des blocs permettent de se repérer)

**Comment by goetsu** [comment]
bloc avec visionneuse
cas image - sans alt contribué sans légende sans crédit -> ok (à noter la numérotation démarre à 2 au lieu de 1), utiliser le alt générique de l'image "image x" dans la visionneuse pour etre cohérent et non "illustration"
cas Image - sans alt contribué sans légende avec crédit -> préciser "droits réservés" au lieu de © dans le aria-label du figure, générer le © via un <span aria-hidden="true"></span> dans le crédit utiliser le alt générique de l'image "image x" dans la visionneuse pour etre cohérent et non "illustration"
cas Image - sans alt contribué avec legende sans crédit -> utiliser le alt générique de l'image "image x" dans la visionneuse pour etre cohérent et non "illustration"
cas Image - sans alt contribué avec legende avec crédit -> ajouter le crédit dans le aria-label en précisant "droits réservés" au lieu de ©, générer le © via un <span aria-hidden="true"></span> dans le crédit, utiliser le alt générique de l'image "image x" dans la visionneuse pour etre cohérent et non "illustration"

cas image - avec alt contribué sans légende sans crédit -> le alt n'a pas l'air contribué
cas Image - avec alt contribué sans légende avec crédit -> utiliser le crédit dans le aria-label du figure au lieu du alt de l'image en précisant "droits réservés" au lieu de ©, générer le © via un <span aria-hidden="true"></span>
cas mage - avec alt contribué avec legende sans crédit -> ok
cas image - avec alt contribué avec legende avec crédit-> ajouter le crédit dans le aria-label en précisant "droits réservés" au lieu de ©, générer le © via un <span aria-hidden="true"></span> dans le crédit, ajouter alt générique sur l'image type "image x" où x numéro de l'image dans la page

cas galerie sans alt
* cas image sans legende sans crédit -> ok
* cas image avec crédit -> préciser "droits réservés" au lieu de © dans le aria-label du figure, ajouter alt générique sur l'image type "image", générer le © dans le crédit via un <span aria-hidden="true"></span>
* cas image  avec légende -> ajouter alt générique sur l'image type "image x" où x numéro de l'image dans la page
* cas image avec légende et crédit -> ajouter le crédit dans le aria-label en précisant "droits réservés" au lieu de ©, générer le © via un <span aria-hidden="true"></span> dans le crédit, ajouter alt générique sur l'image type "image x" où x numéro de l'image dans la page

cas galerie avec alt 
* cas image sans legend sans crédit -> supprimer le role figure et le aria-label du figure
* cas image avec crédit -> utiliser le crédit dans le aria-label du figure au lieu du alt de l'image en précisant "droits réservés" au lieu de ©, générer le © via un <span aria-hidden="true"></span>
* cas image avec légende -> ok
* cas image avec legende et crédit -> ajouter le crédit dans le aria-label en précisant "droits réservés" au lieu de ©, générer le © via un <span aria-hidden="true"></span>

**Comment by alexisben** [comment]
- [x] utiliser le alt générique de l'image "image x" dans la visionneuse pour être cohérent
- [x] préciser "droits réservés" au lieu de © dans le aria-label du figure
- [ ] générer le © via un dans le crédit
- [x] cas image sans legend sans crédit -> supprimer le role figure et le aria-label du figure
- [ ] cas image avec crédit -> utiliser le crédit dans le aria-label du figure au lieu du alt de l'image
- [ ] cas image avec legende et crédit -> ajouter le crédit dans le aria-label

**Comment by alexisben** [comment]
@goetsu je me demande pour la règle du aria-label des `figure`. Est-ce plutôt que de concaténer la légende et le crédit dans le `aria-label` on ne peut pas faire un `aria-labelledby` vers l'id du `figcaption` qui contient ces mêmes informations ?

**Comment by goetsu** [comment]
formellement il y a dans le rgaa
"Les attributs WAI-ARIA aria-labelledby et aria-describedby ne peuvent pas être utilisés actuellement par manque de support par les technologies d’assistance."
Cette assertion n'est sans doute plus vrai à l'heure actuelle mais faute de mise à jour du RGAA malheureusement si vous voulez etre conforme cela n'est pas possible

**Comment by alexisben** [comment]
Ok d'accord merci ! Ça fera du bien au DOM lorsqu'ils feront évoluer ce point !

Il nous manque un point :
> générer le © via un `<span aria-hidden="true"></span>`  dans le crédit

C'est assez compliqué car le crédit est fourni avec le balisage html (dont des `<p>`). Si le lecteur d'écran ne lit pas le "©" injecté en CSS , via le `content: © / "" ` (on a testé sur NVDA et VoiceOver) est-ce conforme ?

**Comment by alexisben** [comment]
> Ok d'accord merci ! Ça fera du bien au DOM lorsqu'ils feront évoluer ce point !
> 
> Il nous manque un point :
> 
> > générer le © via un `<span aria-hidden="true"></span>`  dans le crédit
> 
> C'est assez compliqué car le crédit est fourni avec le balisage html (dont des `<p>`). Si le lecteur d'écran ne lit pas le "©" injecté en CSS , via le `content: © / "" ` (on a testé sur NVDA et VoiceOver) est-ce conforme ?

On a trouvé une solution technique pour palier, on ajoute bien les "©" dans un span en aria-hidden

**Comment by goetsu** [comment]
c'est ok hormis ce point : 
(à noter la numérotation démarre à 2 au lieu de 1)
