### ISSUE TITLE
Visionneuse

### ISSUE THREAD

**Issue by goetsu** [osunyorg/theme#761]
https://example.osuny.org/fr/actualites/2024-11-18-la-nouvelle-visionneuse-dosuny/

- l'image devrait avoir un alt générique "illustration" ou mieux, si une alternative à l'image est contribué en back office (qui n'est pas la légende) alors c'est cette alternative qui se retrouve dans le alt de l'image (conformité)
- si il y a une légende ou des crédits ajouter une aria-describedby sur l'image dont la valeur sur lightbox-information (si légende seule) lightbox-credit (si crédit seule) lightbox-information lightbox-credit (si légende et crédit) (conformité)
- remplacer le tabindex="0" sur l'image par un tabindex="-1" (conformité)

**Comment by arnaudlevy** [comment]
## Problème

### URL

https://example.osuny.org/fr/actualites/2024-11-18-la-nouvelle-visionneuse-dosuny/

### Description

Qu'est-ce qui ne va pas ? 

TODO

### Impact

Dans quelle situation ceci est-il gênant ? En vocal ? Au clavier ? Quel handicap ?

TODO

### Nature

Est-ce un problème de conformité RGAA ou une proposition d'amélioration ?
Si c'est un problème de conformité, quel est le critère concerné ?

TODO

### Code problématique

Code, éventuellement simplifié, à l'origine du problème.

TODO

```HTML
```

## Solution

### Description

En quoi consiste la solution ?

TODO

### Code cible

À quoi doit ressembler le code après réparation ?

TODO

```HTML
```

### Effet attendu

En quoi est-ce une amélioration pour les personnes impactées ?
Par exemple, quelle est la vocalisation attendue ?

TODO

### Source

D'où vient cette recommandation ? 

TODO

### Exemple d'implémentation

Où peut-on observer cette solution en production ?

TODO

**Comment by alexisben** [comment]
> l'image devrait avoir un alt générique "illustration" ou mieux, si une alternative à l'image est contribué en back office (qui n'est pas la légende) alors c'est cette alternative qui se retrouve dans le alt de l'image (conformité)

Le alt avec un texte comme "illustration" semble être contradictoire avec le [1.1.1](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#1.1.1) et le [1.2.1](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#1.2.1):

> si il y a une légende ou des crédits ajouter une aria-describedby sur l'image dont la valeur sur lightbox-information (si légende seule) lightbox-credit (si crédit seule) lightbox-information lightbox-credit (si légende et crédit) (conformité)

Ok très clair

> remplacer le tabindex="0" sur l'image par un tabindex="-1" (conformité)

Est-ce qu'on peut juste enlever le "tabindex" sur l'image ?

**Comment by goetsu** [comment]
l'image ne peut pas etre décorative dans ce contexte, tu ne peux pas supprimer le tabindex puisque le focus est bougé sur l'image quand on va à image suivante / précédente dans la visionneuse

**Comment by alexisben** [comment]
Proposition pour le point du focus : 

- à l'ouverture de la visionneuse, la balise `img` n'a pas de `tabindex` et n'est donc pas focusable.
- si l'on navigue via la visionneuse, on ajoute un `tabindex=0` et on focus l'élément. 

Est-ce correct @goetsu ?

**Comment by goetsu** [comment]
tabindex -1 pas 0

**Comment by alexisben** [comment]
Mais comment je focus l'image avec un `tabindex=-1` ? Ou alors il faut nous dire où placer le focus si ce n'est pas sur l'image ?

**Comment by goetsu** [comment]
tabindex -1 permet de rendre focusable un élément via javascript sans qu'il devienne focusable dans le flux naturel ce qui est le but recherché ici

**Comment by alexisben** [comment]
Ah super ! On ne savait pas que c'était permis. J'ai mis à jour le thème avec les correctitfs du `tabindex` et du `aria-describedby`

**Comment by goetsu** [comment]
c'est ok sur ces deux correctifs, reste le alt générique à prévoir

**Comment by arnaudlevy** [comment]
@goetsu cf https://github.com/osunyorg/theme/issues/760#issuecomment-2498722826

**Comment by alexisben** [comment]
@goetsu je crois qu'on est tout bon pour ce point, tu confirmes ?

**Comment by arnaudlevy** [comment]
Ben moi je vous suis !

**Comment by arnaudlevy** [comment]
Ben moi je vous suis !
