### ISSUE TITLE
Langue des noms de réseaux sociaux

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/theme#790]
Est-ce que ça pourrait être une bonne idée de rajouter du `lang="en"` sur les réseaux sociaux dont le nom sonne mieux en anglais ? Je viens d’écouter voiceOver dire “linquedin” ou “tikteauk” et c’est quand même pas terrible (par contre il prononce très bien facebook)

(je ne sais pas si c'est possible dans un title ceci dit)

**Comment by goetsu** [comment]
mauvaise idée dans la mesure ou le title est en français

**Comment by Olivia206** [comment]
Est-ce qu'il y a un moyen de palier ça, pour rendre la lecture argéable, @goetsu ?

**Comment by Olivia206** [comment]
Donc ça ne rentre pas dans la non conformité du critère 8.7 ?

**Comment by goetsu** [comment]
non les noms propre sont dans les cas particuliers

**Comment by Olivia206** [comment]
Ok, bien noté, merci du retour

**Comment by arnaudlevy** [comment]
Merci @goetsu et @Olivia206 !
