### ISSUE TITLE
CTA collé en bas de page

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/theme#812]
En mobile et en desktop avec sidebar, le CTA est collé en bas.
Il y avait une logique quand il avait un background, mais là ça dépend du layout.
Il faut peut-être ajuster le sélecteur pour s'appuyer sur la présence ou l'absence de bg.

<img width="398" alt="Capture d’écran 2024-12-10 à 09 19 13" src="https://github.com/user-attachments/assets/e00beb92-3e1e-404f-904f-bef92dad7a4b">

**Comment by arnaudlevy** [comment]
J'ai ajouté du CSS pour patcher

**Comment by Olivia206** [comment]
Coucou @arnaudlevy, j'ai envoyé le petit fix en ligne :)

**Comment by arnaudlevy** [comment]
J'ai pas tout bien compris mais merci !
