### ISSUE TITLE
Titre des blocs : ajuster les clés`ranks`

### ISSUE THREAD

**Issue by alexisben** [osunyorg/theme#818]
Dans un bloc, la clé `self` renvoie toujours une valeur, même si le bloc n'a pas de titre.

Par contre les blocs n'ayant pas de titre enfant, n'ont pas de `ranks.children`.

- S'il n'y pas de titre au bloc, il faut masquer `ranks.self`
- Pour le bloc contact, il faut ajouter le `ranks.children` 

Ces changements impliquent de reprendre le partial "block/contact" :

avant : 
```
        {{ $heading_rank := $block.ranks.self }}
        {{ if $block.title }}
          {{ $heading_rank = $block.ranks.self | add 1 }}
        {{ end }}
```

après : 
```
        {{ $heading_rank := $block.ranks.children }}
```

**Comment by arnaudlevy** [comment]
https://github.com/osunyorg/theme/pull/823
